version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    command: npm run serve
